### ISSUE TITLE
fork_tree has a bug again

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#1056]
> Error: panicked at 'invalid key', /home/pierre/Projets/smoldot/src/chain/fork_tree.rs:329:13

**Comment by tomaka** [comment]
`Error: panicked at 'assertion failed: self.tree.nodes.get(self.tree.first_root.unwrap()).is_some()', /home/pierre/Projets/substrate-lite/src/chain/fork_tree.rs:548:13`

**Comment by tomaka** [comment]
I've been unable to reproduce this for a long time now.
