### ISSUE TITLE
Smoldot panic at called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by shibshib** [paritytech/smoldot#1604]
Trying smoldot light client with a substrate chain built using the `substrate-node-template`. 

```
[smoldot_light] Chain initialization complete for nakamoto_mainnet. Name: "Nakamoto Bittensor Mainnet". Genesis hash: 0xadcb…c667. Network identity: 12D3KooWJRnKpGZktFqDcrDCzHX4GZhHx1ZuAh7qNzSMYnG5zQbn. Starting at block #0 (0xadcb…c667)
[network] Connected to 12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A
[network] Connected to 12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc
Smoldot has panicked. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
Error: panicked at 'called `Option::unwrap()` on a `None` value', /root/smoltensor/src/transactions/light_pool.rs:448:80
    at panic (file:///root/smoltensor/bin/wasm-node/javascript/src/bindings-smoldot-light.js:41:19)
    at _ZN13smoldot_light3ffi5panic17h7a09c05741620fdbE (wasm://wasm/15814e8e:wasm-function[1509]:0x154c76)
    at _ZN13smoldot_light6Client3new28_$u7b$$u7b$closure$u7d$$u7d$17h922816e438ce8b07E (wasm://wasm/15814e8e:wasm-function[1772]:0x1875a9)
    at _ZN3std9panicking20rust_panic_with_hook17h980095d26a8973b9E (wasm://wasm/15814e8e:wasm-function[4878]:0x3a4f04)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h93acab47b822d060E (wasm://wasm/15814e8e:wasm-function[4866]:0x3a46a4)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h0e423f4bf0c51c61E (wasm://wasm/15814e8e:wasm-function[4865]:0x3a461b)
    at rust_begin_unwind (wasm://wasm/15814e8e:wasm-function[4877]:0x3a4df6)
    at _ZN4core9panicking9panic_fmt17h5e9d27e9ecfd2231E (wasm://wasm/15814e8e:wasm-function[4997]:0x3b1116)
    at _ZN4core9panicking5panic17h1bdbb40f25a1c647E (wasm://wasm/15814e8e:wasm-function[4983]:0x3ac219)
    at _ZN7smoldot12transactions10light_pool26LightPool$LT$TTx$C$TBl$GT$14set_best_block17he90f176026368cd6E (wasm://wasm/15814e8e:wasm-function[1594]:0x15e540)
Smoldot appears unresponsive. Please open an issue at https://github.com/paritytech/smoldot/issues. If you have a debugger available, please pause execution, generate a stack trace of the thread that isn't the main execution thread, and paste it in the issue. Please also include any other log found in the console or elsewhere.
```
Not entirely sure if this is a known bug or if this is new.

**Comment by shibshib** [comment]
Actually one thing that could be of interest. The chain I'm connecting it to isn't a relay chain (yet), meaning it's a modified substrate node template that likely isn't cumulus compatible yet. Is this an issue?

**Comment by tomaka** [comment]
It should work nonetheless.

**Comment by shibshib** [comment]
I see. I traced it and it looks like it's failing here: 

```
#[must_use]
    pub fn set_best_block(&mut self, new_best_block_hash: &[u8; 32]) -> SetBestBlock {
-->        let new_best_block_index = *self.blocks_by_id.get(new_best_block_hash).unwrap();

```

Maybe because the boot nodes it's connecting to are not archiving the entire blockchain and so it is asking for a block that they do not have?

**Comment by tomaka** [comment]
No, it's an internal error within smoldot. The code that notifies of new blocks notifies them in the wrong order, or some similar issue.

**Comment by shibshib** [comment]
Ahhhh. Damn. 

Any suggested workaround? Perhaps I can contribute a fix, but I'm not sure where to start debugging this.

**Comment by tomaka** [comment]
Giving me a way to reproduce would be great.

Otherwise, you can:
- Clone smoldot
- Change `../../westend.json` [here](https://github.com/paritytech/smoldot/blob/5f7724f9ca8c985fdfea960592b37319843bdf32/bin/wasm-node/javascript/demo/demo.js#L27) to be a path that points to your chain spec
- Change the log level [here](https://github.com/paritytech/smoldot/blob/5f7724f9ca8c985fdfea960592b37319843bdf32/bin/wasm-node/javascript/demo/demo.js#L36) from 3 to 4
- Start the demo (`npm install` then `npm start`) from that directory.
- Once it crashes, copy paste here the logs that the node has printed.

**Comment by shibshib** [comment]
Thanks @tomaka !

This is what I have:

```
[connections] Pending(PendingId(0), 12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) started: /dns4/kenobi.nakamoto.opentensor.ai/tcp/30333/ws
[connections] Pending(PendingId(1), 12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) started: /dns4/skywalker.nakamoto.opentensor.ai/tcp/30333/ws
[smoldot_light] Chain initialization complete for nakamoto_mainnet. Name: "Nakamoto Bittensor Mainnet". Genesis hash: 0xadcb…c667. Network identity: 12D3KooWDcAPuFNfgnkfKFLXcRWwHQJkuBGGY28Ypij5hXdirpyX. Starting at block #0 (0xadcb…c667)
[runtime-nakamoto_mainnet] Reinitialized background worker to finalized block 0xadcb…c667
[runtime-nakamoto_mainnet] Starting new download, id=DownloadId(0), block=0xadcb…c667
[runtime-nakamoto_mainnet] Failed to download :code and :heappages of block: No node available for storage query
[tx-service-nakamoto_mainnet] Transactions watcher moved to finalized block 0xadcb…c667.
[connections] Pending(PendingId(0), 12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => Connection(ConnectionId(0)) through /dns4/kenobi.nakamoto.opentensor.ai/tcp/30333/ws
[connections] Pending(PendingId(1), 12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => Connection(ConnectionId(1)) through /dns4/skywalker.nakamoto.opentensor.ai/tcp/30333/ws
[network] Connected to 12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A, nakamoto_mainnet) => ChainConnected(55821, 0xaf1b…7b1f)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connected to 12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc, nakamoto_mainnet) => ChainConnected(55821, 0xaf1b…7b1f)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => IdentifyRequest
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => IdentifyRequest
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(12D3KooWDWw2Ph2JLHFxNUAhLpgGf2HAE2BHjXkoaj7HS9HapKnc) => GrandpaWarpSyncRequest(Err(Request(Connection(ProtocolNotAvailable))))
[network] Connection(12D3KooWASPUokJTdXKKYvBhkcX4JxNVfaN9WUqZuoL33NJQEu7A) <= GrandpaWarpSyncRequest(0xadcb…c667)
[network] Connection(?, nakamoto_mainnet) => GrandpaCommitMessage(0xfdb0…dbf0)
Smoldot has panicked. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
Error: panicked at 'called `Option::unwrap()` on a `None` value', /Users/alashaabana/.bittensor/smoltensor/src/transactions/light_pool.rs:448:80
    at panic (file:///Users/alashaabana/.bittensor/smoltensor/bin/wasm-node/javascript/src/bindings-smoldot-light.js:41:19)
    at _ZN13smoldot_light3ffi5panic17h82e080a1d20fdfd2E (wasm://wasm/157b202a:wasm-function[1521]:0x158860)
    at _ZN13smoldot_light6Client3new28_$u7b$$u7b$closure$u7d$$u7d$17h594d130eb5e01262E (wasm://wasm/157b202a:wasm-function[1783]:0x18b130)
    at _ZN3std9panicking20rust_panic_with_hook17h980095d26a8973b9E (wasm://wasm/157b202a:wasm-function[4875]:0x3a3f0e)
    at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h93acab47b822d060E (wasm://wasm/157b202a:wasm-function[4863]:0x3a36ae)
    at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h0e423f4bf0c51c61E (wasm://wasm/157b202a:wasm-function[4862]:0x3a3625)
    at rust_begin_unwind (wasm://wasm/157b202a:wasm-function[4874]:0x3a3e00)
    at _ZN4core9panicking9panic_fmt17h5e9d27e9ecfd2231E (wasm://wasm/157b202a:wasm-function[4994]:0x3b0120)
    at _ZN4core9panicking5panic17h1bdbb40f25a1c647E (wasm://wasm/157b202a:wasm-function[4980]:0x3ab223)
    at _ZN7smoldot12transactions10light_pool26LightPool$LT$TTx$C$TBl$GT$14set_best_block17h5525969d684dd786E (wasm://wasm/157b202a:wasm-function[1606]:0x16212a)
Smoldot appears unresponsive. Please open an issue at https://github.com/paritytech/smoldot/issues. If you have a debugger available, please pause execution, generate a stack trace of the thread that isn't the main execution thread, and paste it in the issue. Please also include any other log found in the console or elsewhere.
```

**Comment by shibshib** [comment]
Digging further, looks like this could be caused primarily by `ProtocolNotAvailable` so likely the problem is with our node-substrate-template blockchain. According to the code `Remote has indicated that it doesn't support the requested protocol.`. What's the protocol that we need to support?

**Comment by tomaka** [comment]
You need to apply roughly this change to your chain's code: https://github.com/paritytech/substrate/pull/8922 (this is an old PR, I'm linking to it just to give you an idea of the lines to add, but please look at a more recent version of Substrate to copy them from)

However the lack of Grandpa warp syncing support shouldn't cause a panic.

**Comment by tomaka** [comment]
The panic is fixed, but as a heads up smoldot will not manage to sync your chain if Grandpa warp syncing is not supported by the nodes.

**Comment by shibshib** [comment]
Thanks @tomaka ! You're a legend. Do you mean grandpa warp syncing on our full nodes or on the light nodes?
