### ISSUE TITLE
Networking debug assert failure

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2292]
```
Error: panicked at 'assertion failed: !connection.shutting_down', /home/tomaka/Projets/smoldot/src/libp2p/collection.rs:1065:21
(demo) Error during JSON-RPC request: Error: Error: panicked at 'assertion failed: !connection.shutting_down', /home/tomaka/Projets/smoldot/src/libp2p/collection.rs:1065:21
```

**Comment by tomaka** [comment]
Normally fixed by https://github.com/paritytech/smoldot/pull/2416
