### ISSUE TITLE
Demo client crashed after 40 mins

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2593]
```
$ node demo/demo.mjs
JSON-RPC server now listening on port 9944
Please visit one of:
- westend2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestend2
- westmint: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestmint
- polkadot: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fpolkadot
- acala: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Facala
- ksmcc3: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fksmcc3
- statemine: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fstatemine
- karura: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fkarura
- rococo_v2_2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Frococo_v2_2
- adz_rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fadz_rococo
- canvas-rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fcanvas-rococo

[10:49:02.262] [smoldot] Smoldot v0.6.27
[10:49:02.336] [smoldot] Chain initialization complete for westend2. Name: "Westend". Genesis hash: 0xe143…423e. State root hash: 0x7e92439a94f79671f9cade9dff96a094519b9001a7432244d46ab644bb6f746f. Network identity: 12D3KooWRse9u6Z9ukP4C92YCCH2gXziNm8ThRch2owaaFh9H6D1. Chain specification or database starting at: 0xf55e…a836 (#11771600)
[10:49:02.336] [smoldot] Chain westend2 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:49:03.785] [smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWNicu1ZCX6ZNUC96B4TQSiet2NkoQc7SfitxWWE4fQgpK. Chain specification or database starting at: 0xd359…ac08 (#9768333)
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:49:04.422] [smoldot] Chain initialization complete for ksmcc3. Name: "Kusama". Genesis hash: 0xb0a8…dafe. State root hash: 0xb0006203c3a6e6bd2c6a17b1d4ae8ca49a31da0f4579da950b127774b44aef6b. Network identity: 12D3KooWN1F4dvoozSHHEN2VuLYAUZyXGa6UQxa2QhAZCRtjkmN5. Chain specification or database starting at: 0xb6ca…fe2a (#13626505)
[10:49:04.422] [smoldot] Chain ksmcc3 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[10:49:08.640] [sync-service-westend2] GrandPa warp sync finished to #12068455 (0xdcf7…265d)
[10:49:09.661] [runtime-westend2] Finalized block runtime ready. Spec version: 9270. Size of `:code`: 1.1 MiB.
[10:49:18.797] [sync-service-polkadot] GrandPa warp sync still in progress and taking a long time
[10:49:19.484] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[10:49:29.625] [sync-service-polkadot] GrandPa warp sync finished to #11507887 (0xedfd…7b22)
[10:49:30.606] [runtime-polkadot] Finalized block runtime ready. Spec version: 9250. Size of `:code`: 1.2 MiB.
[10:49:30.927] [smoldot] Parachain initialization complete for acala. Name: "Acala". Genesis hash: 0xfc41…a64c. State root hash: 0x010c5745a5d42bcfbe0a644d5a2a4e22e2ff0fd378d48208ecfacea5b7e05a74. Network identity: 12D3KooWQfQwmPeC2GFJZtnvJaSwrLVc2nCcV8UYVVSusqq48fbQ. Relay chain: polkadot (id: 2000)
[10:49:30.927] [smoldot] Chain acala has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[10:49:34.641] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[10:49:37.493] [sync-service-ksmcc3] GrandPa warp sync finished to #13908433 (0xa633…e61f)
[10:49:38.525] [runtime-ksmcc3] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.3 MiB.
[10:49:38.542] [smoldot] Parachain initialization complete for karura. Name: "Karura". Genesis hash: 0xbaf5…126b. State root hash: 0x388e346937d485c71c53c80ca8e1aca55f3857a55efe3d3baf86371b14067318. Network identity: 12D3KooWJtpWzB9dMpweNWim6qqkMLWDxfeVociQ9rZ6nHK5NGMR. Relay chain: ksmcc3 (id: 2000)
[10:49:42.861] [runtime-acala] Successfully compiled runtime. Spec version: 2000. Size of `:code`: 1.1 MiB.
[10:49:49.991] [runtime-karura] Successfully compiled runtime. Spec version: 1000. Size of `:code`: 2.0 MiB.
[10:50:02.334] [smoldot] Smoldot v0.6.27. Current memory usage: 582 MiB. Average download: 660 kiB/s. Average upload: 1.8 kiB/s.
[10:51:02.335] [smoldot] Smoldot v0.6.27. Current memory usage: 582 MiB. Average download: 60.8 kiB/s. Average upload: 904 B/s.
[10:52:02.338] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 66.2 kiB/s. Average upload: 914 B/s.
[10:53:02.339] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 71.8 kiB/s. Average upload: 1.2 kiB/s.
[10:53:41.845] [json-rpc-karura] JSON-RPC call not supported yet: system_networkState
[10:53:44.058] [json-rpc-karura] JSON-RPC call not supported yet: system_nodeRoles
[10:54:02.339] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 64.3 kiB/s. Average upload: 878 B/s.
[10:55:02.344] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 63.8 kiB/s. Average upload: 939 B/s.
[10:56:02.354] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 68.7 kiB/s. Average upload: 1.0 kiB/s.
[10:57:02.355] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 56.2 kiB/s. Average upload: 872 B/s.
[10:58:02.359] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 63.2 kiB/s. Average upload: 971 B/s.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:59:02.364] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 101 kiB/s. Average upload: 4.0 kiB/s.
[11:00:02.376] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 82.5 kiB/s. Average upload: 4.5 kiB/s.
[11:01:02.391] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 107 kiB/s. Average upload: 4.8 kiB/s.
[11:02:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 121 kiB/s. Average upload: 6.0 kiB/s.
[11:03:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 131 kiB/s. Average upload: 7.5 kiB/s.
[11:04:02.400] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 133 kiB/s. Average upload: 7.7 kiB/s.
[11:05:02.399] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 135 kiB/s. Average upload: 7.8 kiB/s.
[11:06:02.408] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 149 kiB/s. Average upload: 8.8 kiB/s.
[11:07:02.291] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 151 kiB/s. Average upload: 9.6 kiB/s.
[11:08:02.290] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 152 kiB/s. Average upload: 9.6 kiB/s.
[11:09:02.310] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 142 kiB/s. Average upload: 8.9 kiB/s.
[11:10:02.318] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 150 kiB/s. Average upload: 8.6 kiB/s.
[11:11:02.322] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 142 kiB/s. Average upload: 8.5 kiB/s.
[11:12:02.357] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 155 kiB/s. Average upload: 8.9 kiB/s.
[11:13:02.368] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 9.1 kiB/s.
[11:14:02.369] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 152 kiB/s. Average upload: 9.5 kiB/s.
[11:15:02.375] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 8.1 kiB/s.
[11:16:02.383] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 148 kiB/s. Average upload: 9.2 kiB/s.
[11:17:02.395] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 153 kiB/s. Average upload: 9.0 kiB/s.
[11:18:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 139 kiB/s. Average upload: 7.6 kiB/s.
[11:19:02.408] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 150 kiB/s. Average upload: 8.3 kiB/s.
[11:20:02.406] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 164 kiB/s. Average upload: 10.2 kiB/s.
[11:21:02.409] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 155 kiB/s. Average upload: 8.7 kiB/s.
[11:22:02.407] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 8.8 kiB/s.
[11:23:02.624] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 151 kiB/s. Average upload: 8.7 kiB/s.
[11:24:02.626] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 167 kiB/s. Average upload: 10.1 kiB/s.
[11:25:02.630] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 131 kiB/s. Average upload: 7.8 kiB/s.
[11:26:02.657] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 186 kiB/s. Average upload: 11.8 kiB/s.
[11:27:02.678] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 146 kiB/s. Average upload: 8.7 kiB/s.
[11:28:02.680] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 160 kiB/s. Average upload: 8.4 kiB/s.
[11:29:02.681] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 114 kiB/s. Average upload: 8.4 kiB/s.
[11:30:02.834] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 114 kiB/s. Average upload: 9.0 kiB/s.
[11:31:02.847] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 119 kiB/s. Average upload: 9.7 kiB/s.
[11:32:02.849] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 105 kiB/s. Average upload: 8.4 kiB/s.
[11:33:02.866] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 117 kiB/s. Average upload: 9.7 kiB/s.
Smoldot has panicked while executing task `network-service`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
panicked at 'assertion failed: matches!(v.open, NotificationsOutOpenState :: Closed)', /Users/xiliangchen/projects/smoldot/src/libp2p/peers.rs:378:33
(demo) Error during JSON-RPC request: Error: panicked at 'assertion failed: matches!(v.open, NotificationsOutOpenState :: Closed)', /Users/xiliangchen/projects/smoldot/src/libp2p/peers.rs:378:33
```

**Comment by xlc** [comment]
Got another crash

```
$ node demo/demo.mjs 
JSON-RPC server now listening on port 9944
Please visit one of:
- westend2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestend2
- westmint: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestmint
- polkadot: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fpolkadot
- acala: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Facala
- ksmcc3: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fksmcc3
- statemine: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fstatemine
- karura: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fkarura
- rococo_v2_2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Frococo_v2_2
- adz_rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fadz_rococo
- canvas-rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fcanvas-rococo

[21:00:16.012] [smoldot] Smoldot v0.6.27
[21:00:16.086] [smoldot] Chain initialization complete for westend2. Name: "Westend". Genesis hash: 0xe143…423e. State root hash: 0x7e92439a94f79671f9cade9dff96a094519b9001a7432244d46ab644bb6f746f. Network identity: 12D3KooWRse9u6Z9ukP4C92YCCH2gXziNm8ThRch2owaaFh9H6D1. Chain specification or database starting at: 0xf55e…a836 (#11771600)
[21:00:16.086] [smoldot] Chain westend2 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[21:00:21.779] [sync-service-westend2] GrandPa warp sync finished to #12074567 (0x958e…1c2b)
[21:00:22.263] [runtime-westend2] Finalized block runtime ready. Spec version: 9270. Size of `:code`: 1.1 MiB.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[21:00:28.937] [smoldot] Chain initialization complete for ksmcc3. Name: "Kusama". Genesis hash: 0xb0a8…dafe. State root hash: 0xb0006203c3a6e6bd2c6a17b1d4ae8ca49a31da0f4579da950b127774b44aef6b. Network identity: 12D3KooWQBvigEVJTUXd3PH76tDK1JNU4pCNnP1Hydy517Ww1vYg. Chain specification or database starting at: 0xb6ca…fe2a (#13626505)
[21:00:28.937] [smoldot] Chain ksmcc3 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[21:00:44.212] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[21:00:56.463] [sync-service-ksmcc3] GrandPa warp sync finished to #13914535 (0xc72d…52c1)
[21:00:57.327] [runtime-ksmcc3] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.3 MiB.
[21:00:57.337] [smoldot] Parachain initialization complete for statemine. Name: "Statemine". Genesis hash: 0x4823…771a. State root hash: 0x299ac939ea4722d1fcf7f4873675040ebc83d144620c76206dbeb7468cf30cdf. Network identity: 12D3KooWNKTx2E4g65inx6nb8BX4efprbPVJyvSMQbj6PRH6uTau. Relay chain: ksmcc3 (id: 1000)
[21:01:09.080] [runtime-statemine] Successfully compiled runtime. Spec version: 2. Size of `:code`: 755 kiB.
[21:01:16.085] [smoldot] Smoldot v0.6.27. Current memory usage: 304 MiB. Average download: 421 kiB/s. Average upload: 1.3 kiB/s.
[21:02:16.088] [smoldot] Smoldot v0.6.27. Current memory usage: 305 MiB. Average download: 49.1 kiB/s. Average upload: 1.0 kiB/s.
[21:03:16.090] [smoldot] Smoldot v0.6.27. Current memory usage: 305 MiB. Average download: 43.9 kiB/s. Average upload: 1.3 kiB/s.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[21:03:19.040] [smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWLpEHXXNU4hxRm8cEYR6KacAFCtw8tcsjmAD4VUmormUE. Chain specification or database starting at: 0xd359…ac08 (#9768333)
[21:03:34.179] [sync-service-polkadot] GrandPa warp sync still in progress and taking a long time
[21:03:46.127] [sync-service-polkadot] GrandPa warp sync finished to #11513966 (0x2185…b8a2)
[21:03:46.422] [runtime-polkadot] Finalized block runtime ready. Spec version: 9250. Size of `:code`: 1.2 MiB.
[21:03:46.444] [smoldot] Parachain initialization complete for acala. Name: "Acala". Genesis hash: 0xfc41…a64c. State root hash: 0x010c5745a5d42bcfbe0a644d5a2a4e22e2ff0fd378d48208ecfacea5b7e05a74. Network identity: 12D3KooWRUec2csLQZRMupQMokTgBcUaPasFtc4MHeVQVkoBD2bh. Relay chain: polkadot (id: 2000)
[21:03:46.445] [smoldot] Chain acala has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[21:03:58.231] [runtime-acala] Successfully compiled runtime. Spec version: 2000. Size of `:code`: 1.1 MiB.
[21:04:16.095] [smoldot] Smoldot v0.6.27. Current memory usage: 558 MiB. Average download: 261 kiB/s. Average upload: 1.9 kiB/s.
[21:05:16.099] [smoldot] Smoldot v0.6.27. Current memory usage: 558 MiB. Average download: 69.3 kiB/s. Average upload: 1.8 kiB/s.
[21:06:16.101] [smoldot] Smoldot v0.6.27. Current memory usage: 558 MiB. Average download: 60.4 kiB/s. Average upload: 1.7 kiB/s.
[21:07:16.104] [smoldot] Smoldot v0.6.27. Current memory usage: 558 MiB. Average download: 60.0 kiB/s. Average upload: 1.7 kiB/s.
[21:08:16.121] [smoldot] Smoldot v0.6.27. Current memory usage: 559 MiB. Average download: 56.3 kiB/s. Average upload: 1.7 kiB/s.
[21:09:16.124] [smoldot] Smoldot v0.6.27. Current memory usage: 560 MiB. Average download: 51.2 kiB/s. Average upload: 2.4 kiB/s.
Smoldot has panicked while executing task `connections`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
panicked at 'internal error: entered unreachable code', /Users/xiliangchen/projects/smoldot/src/libp2p/collection/single_stream.rs:384:18
(demo) Error during JSON-RPC request: Error: panicked at 'internal error: entered unreachable code', /Users/xiliangchen/projects/smoldot/src/libp2p/collection/single_stream.rs:384:18
```

**Comment by xlc** [comment]
I am just getting different crashes every time 

```
$ yarn start
yarn run v1.22.17
$ node prepare.mjs --debug && rimraf ./dist && npm run buildModules && node demo/demo.mjs
/Users/xiliangchen/.rustup/toolchains/1.61.0-aarch64-apple-darwin/bin/cargo
info: component 'rust-std' for target 'wasm32-wasi' is up to date
    Finished dev [optimized + debuginfo] target(s) in 0.22s

> @substrate/smoldot-light@0.6.29 buildModules
> tsc -p tsconfig-mjs.json && tsc -p tsconfig-cjs.json && bash fix-package-type.sh

JSON-RPC server now listening on port 9944
Please visit one of:
- westend2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestend2
- westmint: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestmint
- polkadot: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fpolkadot
- acala: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Facala
- ksmcc3: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fksmcc3
- statemine: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fstatemine
- karura: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fkarura
- rococo_v2_2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Frococo_v2_2
- adz_rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fadz_rococo
- canvas-rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fcanvas-rococo

[20:41:10.460] [smoldot] Smoldot v0.6.29
[20:41:10.537] [smoldot] Chain initialization complete for westend2. Name: "Westend". Genesis hash: 0xe143…423e. State root hash: 0x7e92439a94f79671f9cade9dff96a094519b9001a7432244d46ab644bb6f746f. Network identity: 12D3KooWRse9u6Z9ukP4C92YCCH2gXziNm8ThRch2owaaFh9H6D1. Chain specification or database starting at: 0xf55e…a836 (#11771600)
[20:41:10.537] [smoldot] Chain westend2 has bad blocks in its chain specification. Bad blocks are not implemented in the light client.
[20:41:16.350] [sync-service-westend2] GrandPa warp sync finished to #12131976 (0x8130…7da6)
[20:41:16.977] [runtime-westend2] Finalized block runtime ready. Spec version: 9271. Size of `:code`: 1.1 MiB.
[20:42:10.537] [smoldot] Smoldot v0.6.29. Current memory usage: 130 MiB. Average download: 45.7 kiB/s. Average upload: 325 B/s.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[20:42:13.478] [smoldot] Chain initialization complete for ksmcc3. Name: "Kusama". Genesis hash: 0xb0a8…dafe. State root hash: 0xb0006203c3a6e6bd2c6a17b1d4ae8ca49a31da0f4579da950b127774b44aef6b. Network identity: 12D3KooWKHpfkDsB5eg6Nc3gyHEx8yNfjvUnePZwdiz2S4ZXThSt. Chain specification or database starting at: 0xb6ca…fe2a (#13626505)
[20:42:13.478] [smoldot] Chain ksmcc3 has bad blocks in its chain specification. Bad blocks are not implemented in the light client.
[20:42:28.654] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[20:42:44.099] [sync-service-ksmcc3] GrandPa warp sync finished to #13971869 (0x238b…886b)
[20:42:44.813] [runtime-ksmcc3] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.3 MiB.
[20:42:44.820] [smoldot] Parachain initialization complete for karura. Name: "Karura". Genesis hash: 0xbaf5…126b. State root hash: 0x388e346937d485c71c53c80ca8e1aca55f3857a55efe3d3baf86371b14067318. Network identity: 12D3KooWLrmgJpddU5TGyFw2kdCycp57dHCx3uRHsdz34fZNDFib. Relay chain: ksmcc3 (id: 2000)
[20:42:58.292] [runtime-karura] Successfully compiled runtime. Spec version: 2091. Size of `:code`: 1.4 MiB.
[20:43:10.538] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 450 kiB/s. Average upload: 1.3 kiB/s.
[20:44:10.538] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 55.5 kiB/s. Average upload: 739 B/s.
[20:45:10.538] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 49.9 kiB/s. Average upload: 955 B/s.
[20:46:10.539] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 51.6 kiB/s. Average upload: 1.0 kiB/s.
(demo) JSON-RPC client ::ffff:127.0.0.1 disconnected.
[20:47:05.277] [smoldot] Shutting down chain ksmcc3
[20:47:05.278] [smoldot] Shutting down chain karura
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[20:47:06.421] [smoldot] Chain initialization complete for ksmcc3. Name: "Kusama". Genesis hash: 0xb0a8…dafe. State root hash: 0xb0006203c3a6e6bd2c6a17b1d4ae8ca49a31da0f4579da950b127774b44aef6b. Network identity: 12D3KooWGPeM5swsXkXw8rNmXsoWHELnRcKAGjAzaD2V5UesFiV5. Chain specification or database starting at: 0xb6ca…fe2a (#13626505)
[20:47:06.421] [smoldot] Chain ksmcc3 has bad blocks in its chain specification. Bad blocks are not implemented in the light client.
[20:47:10.716] [smoldot] Smoldot v0.6.29. Current memory usage: 164 MiB. Average download: 210 kiB/s. Average upload: 1.1 kiB/s.
[20:47:21.901] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[20:47:37.234] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[20:47:43.244] [sync-service-ksmcc3] GrandPa warp sync finished to #13971919 (0xbc41…c21d)
[20:47:43.540] [runtime-ksmcc3] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.3 MiB.
[20:47:43.550] [smoldot] Parachain initialization complete for karura. Name: "Karura". Genesis hash: 0xbaf5…126b. State root hash: 0x388e346937d485c71c53c80ca8e1aca55f3857a55efe3d3baf86371b14067318. Network identity: 12D3KooWLBzSXcpUeXWAtUQvhCGP65hyJwtDZifReX1hmP2Jttcx. Relay chain: ksmcc3 (id: 2000)
[20:47:55.663] [runtime-karura] Successfully compiled runtime. Spec version: 2091. Size of `:code`: 1.4 MiB.
[20:48:10.718] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 314 kiB/s. Average upload: 1.1 kiB/s.
[20:49:10.719] [smoldot] Smoldot v0.6.29. Current memory usage: 451 MiB. Average download: 53.2 kiB/s. Average upload: 805 B/s.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[20:49:21.960] [smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWEHfmeifNNYNeU1QFDsVBQKaU4QgygUcL4joPQyX3ijkd. Chain specification or database starting at: 0xd359…ac08 (#9768333)
[20:49:36.961] [sync-service-polkadot] GrandPa warp sync still in progress and taking a long time
[20:49:37.675] [sync-service-polkadot] GrandPa warp sync finished to #11570910 (0x45de…5fae)
[20:49:37.928] [runtime-polkadot] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.2 MiB.
[20:50:10.723] [smoldot] Smoldot v0.6.29. Current memory usage: 593 MiB. Average download: 255 kiB/s. Average upload: 2.1 kiB/s.
[20:51:10.724] [smoldot] Smoldot v0.6.29. Current memory usage: 593 MiB. Average download: 81.2 kiB/s. Average upload: 2.7 kiB/s.
[20:52:10.724] [smoldot] Smoldot v0.6.29. Current memory usage: 593 MiB. Average download: 83.2 kiB/s. Average upload: 2.7 kiB/s.
Smoldot has panicked while executing task `json-rpc-karura`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
panicked at 'block already unpinned', /Users/xiliangchen/projects/smoldot/bin/light-base/src/runtime_service.rs:383:29
(demo) Error during JSON-RPC request: Error: panicked at 'block already unpinned', /Users/xiliangchen/projects/smoldot/bin/light-base/src/runtime_service.rs:383:29
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by tomaka** [comment]
These panics all have very different causes. I'm going to close this issue as I've split it into three different issues.
