### ISSUE TITLE
`assertion failed: matches!(v.open, NotificationsOutOpenState :: Closed)`

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2619]
```
$ node demo/demo.mjs
JSON-RPC server now listening on port 9944
Please visit one of:
- westend2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestend2
- westmint: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fwestmint
- polkadot: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fpolkadot
- acala: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Facala
- ksmcc3: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fksmcc3
- statemine: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fstatemine
- karura: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fkarura
- rococo_v2_2: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Frococo_v2_2
- adz_rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fadz_rococo
- canvas-rococo: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fcanvas-rococo

[10:49:02.262] [smoldot] Smoldot v0.6.27
[10:49:02.336] [smoldot] Chain initialization complete for westend2. Name: "Westend". Genesis hash: 0xe143…423e. State root hash: 0x7e92439a94f79671f9cade9dff96a094519b9001a7432244d46ab644bb6f746f. Network identity: 12D3KooWRse9u6Z9ukP4C92YCCH2gXziNm8ThRch2owaaFh9H6D1. Chain specification or database starting at: 0xf55e…a836 (#11771600)
[10:49:02.336] [smoldot] Chain westend2 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:49:03.785] [smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWNicu1ZCX6ZNUC96B4TQSiet2NkoQc7SfitxWWE4fQgpK. Chain specification or database starting at: 0xd359…ac08 (#9768333)
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:49:04.422] [smoldot] Chain initialization complete for ksmcc3. Name: "Kusama". Genesis hash: 0xb0a8…dafe. State root hash: 0xb0006203c3a6e6bd2c6a17b1d4ae8ca49a31da0f4579da950b127774b44aef6b. Network identity: 12D3KooWN1F4dvoozSHHEN2VuLYAUZyXGa6UQxa2QhAZCRtjkmN5. Chain specification or database starting at: 0xb6ca…fe2a (#13626505)
[10:49:04.422] [smoldot] Chain ksmcc3 has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[10:49:08.640] [sync-service-westend2] GrandPa warp sync finished to #12068455 (0xdcf7…265d)
[10:49:09.661] [runtime-westend2] Finalized block runtime ready. Spec version: 9270. Size of `:code`: 1.1 MiB.
[10:49:18.797] [sync-service-polkadot] GrandPa warp sync still in progress and taking a long time
[10:49:19.484] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[10:49:29.625] [sync-service-polkadot] GrandPa warp sync finished to #11507887 (0xedfd…7b22)
[10:49:30.606] [runtime-polkadot] Finalized block runtime ready. Spec version: 9250. Size of `:code`: 1.2 MiB.
[10:49:30.927] [smoldot] Parachain initialization complete for acala. Name: "Acala". Genesis hash: 0xfc41…a64c. State root hash: 0x010c5745a5d42bcfbe0a644d5a2a4e22e2ff0fd378d48208ecfacea5b7e05a74. Network identity: 12D3KooWQfQwmPeC2GFJZtnvJaSwrLVc2nCcV8UYVVSusqq48fbQ. Relay chain: polkadot (id: 2000)
[10:49:30.927] [smoldot] Chain acala has bad blocks in its chain specification. Bad blocks are not implemented in the light client
[10:49:34.641] [sync-service-ksmcc3] GrandPa warp sync still in progress and taking a long time
[10:49:37.493] [sync-service-ksmcc3] GrandPa warp sync finished to #13908433 (0xa633…e61f)
[10:49:38.525] [runtime-ksmcc3] Finalized block runtime ready. Spec version: 9260. Size of `:code`: 1.3 MiB.
[10:49:38.542] [smoldot] Parachain initialization complete for karura. Name: "Karura". Genesis hash: 0xbaf5…126b. State root hash: 0x388e346937d485c71c53c80ca8e1aca55f3857a55efe3d3baf86371b14067318. Network identity: 12D3KooWJtpWzB9dMpweNWim6qqkMLWDxfeVociQ9rZ6nHK5NGMR. Relay chain: ksmcc3 (id: 2000)
[10:49:42.861] [runtime-acala] Successfully compiled runtime. Spec version: 2000. Size of `:code`: 1.1 MiB.
[10:49:49.991] [runtime-karura] Successfully compiled runtime. Spec version: 1000. Size of `:code`: 2.0 MiB.
[10:50:02.334] [smoldot] Smoldot v0.6.27. Current memory usage: 582 MiB. Average download: 660 kiB/s. Average upload: 1.8 kiB/s.
[10:51:02.335] [smoldot] Smoldot v0.6.27. Current memory usage: 582 MiB. Average download: 60.8 kiB/s. Average upload: 904 B/s.
[10:52:02.338] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 66.2 kiB/s. Average upload: 914 B/s.
[10:53:02.339] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 71.8 kiB/s. Average upload: 1.2 kiB/s.
[10:53:41.845] [json-rpc-karura] JSON-RPC call not supported yet: system_networkState
[10:53:44.058] [json-rpc-karura] JSON-RPC call not supported yet: system_nodeRoles
[10:54:02.339] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 64.3 kiB/s. Average upload: 878 B/s.
[10:55:02.344] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 63.8 kiB/s. Average upload: 939 B/s.
[10:56:02.354] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 68.7 kiB/s. Average upload: 1.0 kiB/s.
[10:57:02.355] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 56.2 kiB/s. Average upload: 872 B/s.
[10:58:02.359] [smoldot] Smoldot v0.6.27. Current memory usage: 583 MiB. Average download: 63.2 kiB/s. Average upload: 971 B/s.
(demo) New JSON-RPC client connected: ::ffff:127.0.0.1.
[10:59:02.364] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 101 kiB/s. Average upload: 4.0 kiB/s.
[11:00:02.376] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 82.5 kiB/s. Average upload: 4.5 kiB/s.
[11:01:02.391] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 107 kiB/s. Average upload: 4.8 kiB/s.
[11:02:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 121 kiB/s. Average upload: 6.0 kiB/s.
[11:03:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 131 kiB/s. Average upload: 7.5 kiB/s.
[11:04:02.400] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 133 kiB/s. Average upload: 7.7 kiB/s.
[11:05:02.399] [smoldot] Smoldot v0.6.27. Current memory usage: 586 MiB. Average download: 135 kiB/s. Average upload: 7.8 kiB/s.
[11:06:02.408] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 149 kiB/s. Average upload: 8.8 kiB/s.
[11:07:02.291] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 151 kiB/s. Average upload: 9.6 kiB/s.
[11:08:02.290] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 152 kiB/s. Average upload: 9.6 kiB/s.
[11:09:02.310] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 142 kiB/s. Average upload: 8.9 kiB/s.
[11:10:02.318] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 150 kiB/s. Average upload: 8.6 kiB/s.
[11:11:02.322] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 142 kiB/s. Average upload: 8.5 kiB/s.
[11:12:02.357] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 155 kiB/s. Average upload: 8.9 kiB/s.
[11:13:02.368] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 9.1 kiB/s.
[11:14:02.369] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 152 kiB/s. Average upload: 9.5 kiB/s.
[11:15:02.375] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 8.1 kiB/s.
[11:16:02.383] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 148 kiB/s. Average upload: 9.2 kiB/s.
[11:17:02.395] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 153 kiB/s. Average upload: 9.0 kiB/s.
[11:18:02.396] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 139 kiB/s. Average upload: 7.6 kiB/s.
[11:19:02.408] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 150 kiB/s. Average upload: 8.3 kiB/s.
[11:20:02.406] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 164 kiB/s. Average upload: 10.2 kiB/s.
[11:21:02.409] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 155 kiB/s. Average upload: 8.7 kiB/s.
[11:22:02.407] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 147 kiB/s. Average upload: 8.8 kiB/s.
[11:23:02.624] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 151 kiB/s. Average upload: 8.7 kiB/s.
[11:24:02.626] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 167 kiB/s. Average upload: 10.1 kiB/s.
[11:25:02.630] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 131 kiB/s. Average upload: 7.8 kiB/s.
[11:26:02.657] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 186 kiB/s. Average upload: 11.8 kiB/s.
[11:27:02.678] [smoldot] Smoldot v0.6.27. Current memory usage: 587 MiB. Average download: 146 kiB/s. Average upload: 8.7 kiB/s.
[11:28:02.680] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 160 kiB/s. Average upload: 8.4 kiB/s.
[11:29:02.681] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 114 kiB/s. Average upload: 8.4 kiB/s.
[11:30:02.834] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 114 kiB/s. Average upload: 9.0 kiB/s.
[11:31:02.847] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 119 kiB/s. Average upload: 9.7 kiB/s.
[11:32:02.849] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 105 kiB/s. Average upload: 8.4 kiB/s.
[11:33:02.866] [smoldot] Smoldot v0.6.27. Current memory usage: 588 MiB. Average download: 117 kiB/s. Average upload: 9.7 kiB/s.
Smoldot has panicked while executing task `network-service`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
panicked at 'assertion failed: matches!(v.open, NotificationsOutOpenState :: Closed)', /Users/xiliangchen/projects/smoldot/src/libp2p/peers.rs:378:33
(demo) Error during JSON-RPC request: Error: panicked at 'assertion failed: matches!(v.open, NotificationsOutOpenState :: Closed)', /Users/xiliangchen/projects/smoldot/src/libp2p/peers.rs:378:33
```

_Originally posted by @xlc in https://github.com/paritytech/smoldot/issues/2593_

**Comment by tomaka** [comment]
This _might_ have been addressed by https://github.com/paritytech/smoldot/pull/2610

**Comment by tomaka** [comment]
Just observed it myself. Not fixed.
