### ISSUE TITLE
Race condition in JSON-RPC "connection id" system

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#814]
```
Fri May 07 2021 14:32:54 GMT+0200 (Central European Summer Time) Peer ::ffff:127.0.0.1 disconnected.
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'sendUTF' of undefined
    at Object.json_rpc_callback (file:///home/pierre/Projets/smoldot/bin/wasm-node/javascript/test/demo.js:35:37)
    at Worker.<anonymous> (file:///home/pierre/Projets/smoldot/bin/wasm-node/javascript/src/index.js:83:18)
    at Worker.emit (events.js:315:20)
    at MessagePort.<anonymous> (internal/worker.js:207:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:545:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

The demo is trying to send back an answer on a JSON-RPC connection that no longer exists.

**Comment by tomaka** [comment]
No longer relevant after https://github.com/paritytech/smoldot/pull/994
