### ISSUE TITLE
Various errors on smoldot

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#981]
Following errors appear when running smoldot in browser:
```
bindings-smoldot-js.js:38 Uncaught Error: panicked at 'internal error: entered unreachable code', /__w/smoldot/smoldot/src/sync/all.rs:933:18
    at throw (bindings-smoldot-js.js:38)
    at <anonymous>:wasm-function[443]:0x4b29e
    at <anonymous>:wasm-function[931]:0xa128b
    at <anonymous>:wasm-function[3363]:0x2b54c5
    at <anonymous>:wasm-function[3352]:0x2b4d52
    at <anonymous>:wasm-function[3351]:0x2b4cd3
    at <anonymous>:wasm-function[3362]:0x2b53dd
    at <anonymous>:wasm-function[3436]:0x2bc4a6
    at <anonymous>:wasm-function[3430]:0x2bb8ca
    at <anonymous>:wasm-function[272]:0x27844
```
```
bindings-smoldot-js.js:38 Uncaught Error: panicked at 'invalid key', /__w/smoldot/smoldot/src/chain/fork_tree.rs:456:38
    at throw (bindings-smoldot-js.js:38)
    at <anonymous>:wasm-function[443]:0x4b29e
    at <anonymous>:wasm-function[931]:0xa128b
    at <anonymous>:wasm-function[3363]:0x2b54c5
    at <anonymous>:wasm-function[898]:0xa03d3
    at <anonymous>:wasm-function[897]:0xa03a6
    at <anonymous>:wasm-function[195]:0x1b705
    at <anonymous>:wasm-function[886]:0x9eefb
    at <anonymous>:wasm-function[852]:0x8f925
    at <anonymous>:wasm-function[1096]:0xd68ed
```

**Comment by tomaka** [comment]
First panic is rather unsettling.
Before the panic, we check that the request is indeed a GP warp sync request (https://github.com/paritytech/smoldot/blob/88ba346e3933e4ef4576da56dde694807cb61909/src/sync/all.rs#L922). If anything was wrong in the `sync_service`, it is that one that should panic.
All requests are cleared when transitioning out of GP warp sync (https://github.com/paritytech/smoldot/blob/88ba346e3933e4ef4576da56dde694807cb61909/src/sync/all.rs#L1995), so there shouldn't be any request whose mapping is `RequestMapping::GrandpaWarpSync` afterwards.

**Comment by tomaka** [comment]
First panic fixed by https://github.com/paritytech/smoldot/pull/1060
